apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-rtmp-server.fullname" . }}
  labels:
    {{- include "nginx-rtmp-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-rtmp-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-rtmp-server.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx-rtmp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: rtmp
              containerPort: 1935
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: run
              mountPath: /run/nginx
            - name: cache
              mountPath: /var/cache/nginx
            - name: log
              mountPath: /var/log/nginx
            - name: hls
              mountPath: /var/hls
            - name: dash
              mountPath: /var/dash
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: run
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
        - name: cache
          emptyDir:
            sizeLimit: 64Mi
        - name: log
          emptyDir:
            sizeLimit: 64Mi
        - name: hls
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.hlsVolume.sizeLimit }}
        - name: dash
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.dashVolume.sizeLimit }}
        - name: tmp
          emptyDir:
            sizeLimit: 16Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
